# Generated by Django 4.1 on 2022-10-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True)),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('Email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.IntegerField(blank=True)),
                ('Country', models.CharField(blank=True, max_length=150)),
                ('City', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=150)),
                ('agent_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('amount', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AddEmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True)),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('Email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.IntegerField(blank=True)),
                ('Address', models.CharField(blank=True, max_length=150)),
                ('Country', models.CharField(blank=True, max_length=150)),
                ('City', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=150)),
                ('employee_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=150)),
                ('time', models.TimeField(blank=True, max_length=150)),
                ('amount', models.IntegerField(blank=True)),
                ('agent', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=150)),
                ('time', models.TimeField(blank=True, max_length=150)),
                ('amount', models.IntegerField()),
                ('used_for_purpose', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='myformModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('Email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.IntegerField(blank=True)),
                ('website_name', models.CharField(blank=True, max_length=150)),
                ('my_message', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
