# Generated by Django 4.1 on 2022-10-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addemployeemodel',
            name='user_id',
        ),
    ]
