# Generated by Django 4.1 on 2022-10-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_address_user_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
