# Generated by Django 4.1 on 2022-10-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_addemployeemodel_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addagent',
            name='agent_pic',
        ),
        migrations.RemoveField(
            model_name='addagent',
            name='amount',
        ),
        migrations.AddField(
            model_name='addagent',
            name='employee_pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='addagent',
            name='City',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='addagent',
            name='Country',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='addagent',
            name='Email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='addagent',
            name='password',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='addagent',
            name='phone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='addagent',
            name='user_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='addagent',
            name='user_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
