# Generated by Django 4.1 on 2022-10-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_addagent_agent_pic_remove_addagent_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.TextField(),
        ),
    ]
