# Generated by Django 4.1 on 2022-10-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_addemployeemodel_user_creater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creater',
        ),
    ]
