# Generated by Django 4.1 on 2022-10-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_balance_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='addagent',
            name='amount',
            field=models.TextField(null=True),
        ),
    ]
