# Generated by Django 4.1 on 2022-10-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creater',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
