# Generated by Django 4.1 on 2022-10-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_addagent_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addagent',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
